INSERT INTO ROLES (role_name) VALUES ('SUPER_ADMIN');
INSERT INTO ROLES (role_name) VALUES ('MODERATOR');
INSERT INTO ROLES (role_name) VALUES ('BOOK_AUTHOR');
INSERT INTO ROLES (role_name) VALUES ('CUSTOMER');

