spring:
  application:
    name: authorization-server
  security:
    oauth2:
      client:
        registration:
          custom-google:
            client-id: <client-id>
            client-secret: <secret>
        provider:
          custom-google:
            issuer-uri: https://accounts.google.com